version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: akreditame_user
      POSTGRES_PASSWORD: akreditame_password
      POSTGRES_DB: akreditame_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://akreditame_user:akreditame_password@db:5432/akreditame_db

  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
